version: '1'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_DATABASE: db_wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp

  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: wp
      PMA_PASSWORD: wp

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "3000:80"
    restart: always
    environment:
      WORDPRESS_DB_NAME: db_wp
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
    volumes:
      ["./:/var/www/html"]

volumes:
  db_data:
